language: python

python:
  - "3.6"      # current default Python on Travis CI

# command to install dependencies
install:
  - pip install numpy scipy matplotlib PrettyTable

# command to run tests
script:
  - python -m unittest Testing.test_2D_frames Testing.test_axial_load Testing.test_benchmark Testing.test_end_releases Testing.test_plates Testing.test_springs Testing.test_support_settlement
